[package]
name = "stream-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = "0.3.5"
futures = "0.3.28"
pin-project = "1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7.8", features = ["compat"] }
